"""
Gemini prompt templates for LexAI.

Every prompt:
1. Grounds Gemini in pre-computed structural data from legal_processor.
2. Explicitly forbids inventing facts not in the document.
3. Requests strict JSON output for reliable parsing.
The user-facing disclaimer itself is appended by the endpoint layer
(app.main), never generated by the model.
"""

SIMPLIFY_PROMPT = """You are LexAI, a plain-English legal document
assistant. A user has submitted legal text to be simplified.

Document text:
\"\"\"
{text}
\"\"\"

{focus_instruction}

Your task:
1. Rewrite the key points in plain English a non-lawyer can understand
2. Extract 5-8 key bullet points the user must know
3. DO NOT add information not present in the document
4. Acknowledge complexity honestly — do not oversimplify to the point of inaccuracy

Return ONLY valid JSON:
{{"plain_english": "...", "key_points": ["...", ...]}}"""

ANALYZE_PROMPT = """You are LexAI, reviewing a legal document.
The following structural analysis was computed deterministically:

Stats: {stats}
Risk flags found: {risk_flags}
Obligations found (count): {obligation_count}
Rights found (count): {right_count}
Key dates: {key_dates}

Document text (first 3000 chars): \"\"\"
{text_preview}
\"\"\"

Write a 3-4 sentence plain-English AI summary of what this document
is, who the parties appear to be, and what the user should pay
attention to most. Ground your answer in the structural data above —
do not invent facts.

Return ONLY: {{"ai_summary": "..."}}"""

ASK_PROMPT = """You are LexAI, answering a user's question about a
legal document. Answer ONLY from the document text below.
If the answer is not in the document, say so clearly.
Never invent legal information.

Document:
\"\"\"
{text}
\"\"\"

User question: {question}

Return ONLY valid JSON:
{{"answer": "...",
  "confidence": "high|medium|low — consult a professional"}}"""

COMPARE_PROMPT = """You are LexAI, comparing two legal documents.
Structural analysis (computed, not estimated):

Document A — {label_a}:
{structural_a}

Document B — {label_b}:
{structural_b}

Document A preview: \"\"\"{preview_a}\"\"\"
Document B preview: \"\"\"{preview_b}\"\"\"

Based on the structural data and text previews:
1. Provide an overall comparison paragraph (3-4 sentences)
2. List 4-6 key differences (specific, grounded in the data)
3. Give ONE recommendation on which is more favourable to a
   typical counterparty and why

Return ONLY valid JSON:
{{"ai_comparison": "...",
  "key_differences": ["...", ...],
  "recommendation": "..."}}"""

SUMMARIZE_PROMPT = """You are LexAI, producing an executive summary
of a legal document.

Document text:
\"\"\"
{text}
\"\"\"

Produce:
1. executive_summary: 2-3 sentence overview
2. key_points: 5-8 most important facts from the document
3. important_clauses: names of the 3-5 most significant clauses found
4. action_items: specific actions the user may need to take

Return ONLY valid JSON matching exactly:
{{"executive_summary": "...", "key_points": [...],
  "important_clauses": [...], "action_items": [...]}}"""

PREPARE_PROMPT = """You are LexAI, helping a user prepare to meet
a legal professional about this document.

Document text (first 4000 chars):
\"\"\"
{text_preview}
\"\"\"

Structural risks pre-identified: {risk_categories}

Produce:
1. document_summary: 2-sentence plain summary of what this document is
2. questions_for_lawyer: 6-8 specific, informed questions to ask
3. checklist: 5-6 items the user should prepare or verify before the meeting
4. red_flags: 3-5 specific concerns this document raises

Return ONLY valid JSON:
{{"document_summary": "...", "questions_for_lawyer": [...],
  "checklist": [...], "red_flags": [...]}}"""
